[package]
name = "hotkeynancy"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse"] }
winapi = { version = "0.3.9", features = ["winuser", "windef", "minwindef"] }
